### ISSUE TITLE
How about building a python-based channel models "meta-dataset"?

### ISSUE THREAD

**Issue by yihanjiang** [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL#7]
Right now all AI+communication works are done on a few fixed channels (AWGN, Fading, etc...), while the real environments are dynamic and multi-task-like. 

Is there any good meta-dataset contains a lot of widely accepted channels, as the well-established benchmarks, written in Python (Deep learning in MATLAB is hard...) for us to use? If not, shall we start to write one?

**Comment by zhuwenxing** [comment]
There is [a python version of WINNER II Channel Model](https://github.com/lavaner/pywim2), but the latest update time is four years ago. As I know, the most popular channel model now is  cost2100，but haven't see a python version. furthermore, an open-source nonstationary channel model is needed, both Matlab and python version.

For the second question:
>If not, shall we start to write one?

I would be sorry to say that I am not competent for this hard task because of my poor wireless channel knowledge. But I prefer to think the "we" you mean is the wireless communication community.

**Comment by yihanjiang** [comment]
Thanks!

THen it becomes reasonable and rewarding to start a 'meta-channel' project, which contains multiple channels, in Python. My feeling is, AI-based communication will face multiple channels, then conducting Meta-Learning/Multi-task learning does require a 'meta-channel' dataset.

Let me do this. I will initiate a project on MetaChannels, and play with meta learning on top of it. When the code is verified, I will open-source it, and wait for some suggestion to add more channels.

**Comment by zhuwenxing** [comment]
> Thanks!
> 
> THen it becomes reasonable and rewarding to start a 'meta-channel' project, which contains multiple channels, in Python. My feeling is, AI-based communication will face multiple channels, then conducting Meta-Learning/Multi-task learning does require a 'meta-channel' dataset.
> 
> Let me do this. I will initiate a project on MetaChannels, and play with meta learning on top of it. When the code is verified, I will open-source it, and wait for some suggestion to add more channels.

Hi, you might be interested in this work [Meta-Learning to Communicate: Fast End-to-End Training for Fading Channels](https://arxiv.org/abs/1910.09945), here is the source code [meta-autoencoder](https://github.com/kclip/meta-autoencoder). Hope it helps!
